kind: ServiceAccount
apiVersion: v1
metadata:
  name: delete-namespace-sa
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: delete-namespace-role
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["delete"]
