name: workflow_02
on: [repository_dispatch]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggering Wokflow 2"
      - name: Checkout
        uses: actions/checkout@v2
jobs2:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Payload
        run: echo "Payload: ${{ toJson(github.event.client_payload) }}"
      - name: Checkout Repository
        uses: actions/checkout@v2

